version: '3.8'

services:
  gateway:
    build: .
    container_name: ecommerce-gateway
    ports:
      - "8000:8080"
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/docs || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
