version: "3.9"

services:
  shopcart_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopcart_service
    command: ["sh", "/app/entrypoint.sh"]
    ports:
      - "8080:8080"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./src:/app/src:rw
      - ./uv.lock:/app/uv.lock:rw
      - ./pyproject.toml:/app/pyproject.toml:rw
      - ./.cache/uv:/home/appuser/.cache/uv  # fix permission denied errors
    restart: unless-stopped
